//
// Created by Alex on 2/25/24.
//

#ifndef PRONOUNCE_THIS_SIMPLESPLINEPROFILE_HPP
#define PRONOUNCE_THIS_SIMPLESPLINEPROFILE_HPP


class simpleSplineProfile {

};


#endif //PRONOUNCE_THIS_SIMPLESPLINEPROFILE_HPP
