@startuml

state "Intaking" as intaking
state "Stopped" as stopped
state "Catapult Reload/shoot" as catapult

[*] --> intaking

intaking : speed: 1.0
stopped : speed: 0.0
catapult : speed: -1.0

intaking -> catapult : Catapult shoot
stopped <- intaking : Driver input
stopped -> intaking : Driver input
catapult -> intaking : Catapult reloaded
stopped -> catapult : Fire catapult or reload

@enduml
