#define AUTON_STEAL_LEFT_LEFT_AWP 1
#define AUTON_STEAL_MID_LEFT_AWP 2
#define AUTON_STEAL_MID_RIGHT_AWP 3
#define AUTON_STEAL_RIGHT_RIGHT_AWP 4
#define AUTON_STEAL_RIGHT_RIGHT_RIGHT_AWP 5
#define AUTON_RIGHT_DOUBLE_STEAL 6
#define AUTON_NONE 7
#define AUTON_SKILLS 8
